name: Deploy to Heroku

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_DIR: 'backend'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.APP_DIR }}/package-lock.json'

    - name: npm install, build, and test
      working-directory: ${{ env.APP_DIR }}
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "jengarace"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: ${{ env.APP_DIR }}
